-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lzw_fpga_encoding is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    input_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    input_stream_empty_n : IN STD_LOGIC;
    input_stream_read : OUT STD_LOGIC;
    code_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    code_stream_full_n : IN STD_LOGIC;
    code_stream_write : OUT STD_LOGIC;
    input_size_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size_empty_n : IN STD_LOGIC;
    input_size_read : OUT STD_LOGIC;
    local_output_code_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_output_code_ce0 : OUT STD_LOGIC;
    local_output_code_we0 : OUT STD_LOGIC;
    local_output_code_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_output_size_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_output_size_out_full_n : IN STD_LOGIC;
    local_output_size_out_write : OUT STD_LOGIC;
    local_output_size_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_output_size_out1_full_n : IN STD_LOGIC;
    local_output_size_out1_write : OUT STD_LOGIC );
end;


architecture behav of lzw_fpga_encoding is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_100 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000100000000";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_4 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv23_1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal input_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln35_fu_569_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal code_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln40_1_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_reg_794 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_size_blk_n : STD_LOGIC;
    signal local_output_size_out_blk_n : STD_LOGIC;
    signal local_output_size_out1_blk_n : STD_LOGIC;
    signal input_size_read_reg_747 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_fu_497_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_2_fu_489_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln32_fu_551_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_reg_784 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln40_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_1_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln42_1_fu_605_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_1_reg_802 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_fu_686_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_reg_836 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln42_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln42_reg_841 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln40_fu_728_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln42_1_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_4_fu_734_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln35_1_fu_740_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln32_fu_744_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal table_prefix_code_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_prefix_code_0_ce0 : STD_LOGIC;
    signal table_prefix_code_0_we0 : STD_LOGIC;
    signal table_prefix_code_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_prefix_code_1_ce0 : STD_LOGIC;
    signal table_prefix_code_1_we0 : STD_LOGIC;
    signal table_prefix_code_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_prefix_code_2_ce0 : STD_LOGIC;
    signal table_prefix_code_2_we0 : STD_LOGIC;
    signal table_prefix_code_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_prefix_code_3_ce0 : STD_LOGIC;
    signal table_prefix_code_3_we0 : STD_LOGIC;
    signal table_prefix_code_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_prefix_code_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_character_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_character_0_ce0 : STD_LOGIC;
    signal table_character_0_we0 : STD_LOGIC;
    signal table_character_0_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_character_1_ce0 : STD_LOGIC;
    signal table_character_1_we0 : STD_LOGIC;
    signal table_character_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_character_2_ce0 : STD_LOGIC;
    signal table_character_2_we0 : STD_LOGIC;
    signal table_character_2_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal table_character_3_ce0 : STD_LOGIC;
    signal table_character_3_we0 : STD_LOGIC;
    signal table_character_3_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal table_character_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_reg_412 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i_3_reg_423 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_p_1_phi_fu_444_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_1_reg_435 : STD_LOGIC_VECTOR (31 downto 0);
    signal found_reg_453 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal ap_phi_mux_p_3_phi_fu_468_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_3_reg_465 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln28_fu_518_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln65_fu_580_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln52_fu_616_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln55_fu_651_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln54_fu_631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal table_size_fu_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal table_size_1_fu_666_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op102_write_state5 : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal out_index_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_481_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln55_fu_637_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_60_fu_503_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln29_fu_530_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln29_1_fu_537_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln29_2_fu_544_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln_fu_508_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln32_fu_551_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln35_fu_565_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln40_fu_585_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1_fu_595_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_5_fu_621_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal lshr_ln2_fu_641_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln42_fu_682_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_690_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_690_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_710_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component lzw_fpga_mux_464_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (63 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lzw_fpga_mux_464_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (63 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component lzw_fpga_encoding_table_prefix_code_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lzw_fpga_encoding_table_character_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    table_prefix_code_0_U : component lzw_fpga_encoding_table_prefix_code_0
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_prefix_code_0_address0,
        ce0 => table_prefix_code_0_ce0,
        we0 => table_prefix_code_0_we0,
        d0 => table_prefix_code_0_d0,
        q0 => table_prefix_code_0_q0);

    table_prefix_code_1_U : component lzw_fpga_encoding_table_prefix_code_0
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_prefix_code_1_address0,
        ce0 => table_prefix_code_1_ce0,
        we0 => table_prefix_code_1_we0,
        d0 => table_prefix_code_1_d0,
        q0 => table_prefix_code_1_q0);

    table_prefix_code_2_U : component lzw_fpga_encoding_table_prefix_code_0
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_prefix_code_2_address0,
        ce0 => table_prefix_code_2_ce0,
        we0 => table_prefix_code_2_we0,
        d0 => table_prefix_code_2_d0,
        q0 => table_prefix_code_2_q0);

    table_prefix_code_3_U : component lzw_fpga_encoding_table_prefix_code_0
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_prefix_code_3_address0,
        ce0 => table_prefix_code_3_ce0,
        we0 => table_prefix_code_3_we0,
        d0 => table_prefix_code_3_d0,
        q0 => table_prefix_code_3_q0);

    table_character_0_U : component lzw_fpga_encoding_table_character_0
    generic map (
        DataWidth => 8,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_character_0_address0,
        ce0 => table_character_0_ce0,
        we0 => table_character_0_we0,
        d0 => table_character_0_d0,
        q0 => table_character_0_q0);

    table_character_1_U : component lzw_fpga_encoding_table_character_0
    generic map (
        DataWidth => 8,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_character_1_address0,
        ce0 => table_character_1_ce0,
        we0 => table_character_1_we0,
        d0 => table_character_1_d0,
        q0 => table_character_1_q0);

    table_character_2_U : component lzw_fpga_encoding_table_character_0
    generic map (
        DataWidth => 8,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_character_2_address0,
        ce0 => table_character_2_ce0,
        we0 => table_character_2_we0,
        d0 => table_character_2_d0,
        q0 => table_character_2_q0);

    table_character_3_U : component lzw_fpga_encoding_table_character_0
    generic map (
        DataWidth => 8,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_character_3_address0,
        ce0 => table_character_3_ce0,
        we0 => table_character_3_we0,
        d0 => table_character_3_d0,
        q0 => table_character_3_q0);

    mux_464_32_1_1_U18 : component lzw_fpga_mux_464_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 64,
        dout_WIDTH => 32)
    port map (
        din0 => table_prefix_code_0_q0,
        din1 => table_prefix_code_1_q0,
        din2 => table_prefix_code_2_q0,
        din3 => table_prefix_code_3_q0,
        din4 => tmp_fu_690_p5,
        dout => tmp_fu_690_p6);

    mux_464_8_1_1_U19 : component lzw_fpga_mux_464_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 64,
        dout_WIDTH => 8)
    port map (
        din0 => table_character_0_q0,
        din1 => table_character_1_q0,
        din2 => table_character_2_q0,
        din3 => table_character_3_q0,
        din4 => zext_ln42_reg_836,
        dout => tmp_1_fu_710_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    found_reg_453_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln40_fu_574_p2 = ap_const_lv1_1))) then 
                found_reg_453 <= ap_const_lv31_100;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln42_reg_841 = ap_const_lv1_0) and (icmp_ln40_1_reg_798 = ap_const_lv1_1)) or ((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln42_1_fu_723_p2 = ap_const_lv1_0) and (icmp_ln40_1_reg_798 = ap_const_lv1_1))))) then 
                found_reg_453 <= add_ln40_fu_728_p2;
            end if; 
        end if;
    end process;

    i_3_reg_423_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or ((icmp_ln40_1_reg_798 = ap_const_lv1_0) or ((icmp_ln42_1_fu_723_p2 = ap_const_lv1_1) and (icmp_ln42_reg_841 = ap_const_lv1_1)))))) then 
                i_3_reg_423 <= i_4_fu_734_p2;
            elsif (((input_stream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_3_reg_423 <= ap_const_lv31_1;
            end if; 
        end if;
    end process;

    i_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((input_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_412 <= ap_const_lv9_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0))) then 
                i_reg_412 <= i_2_fu_497_p2;
            end if; 
        end if;
    end process;

    out_index_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_stream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                out_index_fu_142 <= ap_const_lv32_0;
            elsif ((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or (icmp_ln40_1_fu_589_p2 = ap_const_lv1_0)))) then 
                out_index_fu_142 <= grp_fu_481_p2;
            end if; 
        end if;
    end process;

    p_1_reg_435_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or ((icmp_ln40_1_reg_798 = ap_const_lv1_0) or ((icmp_ln42_1_fu_723_p2 = ap_const_lv1_1) and (icmp_ln42_reg_841 = ap_const_lv1_1)))))) then 
                p_1_reg_435 <= zext_ln35_1_fu_740_p1;
            elsif (((input_stream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                p_1_reg_435 <= sext_ln32_fu_551_p1;
            end if; 
        end if;
    end process;

    p_3_reg_465_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln40_reg_794 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln42_1_fu_723_p2 = ap_const_lv1_1) and (icmp_ln42_reg_841 = ap_const_lv1_1) and (icmp_ln40_1_reg_798 = ap_const_lv1_1))) then 
                p_3_reg_465 <= found_reg_453;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                p_3_reg_465 <= zext_ln32_fu_744_p1;
            end if; 
        end if;
    end process;

    table_size_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((input_stream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                table_size_fu_138 <= ap_const_lv32_100;
            elsif ((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
                table_size_fu_138 <= table_size_1_fu_666_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln40_reg_794 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                icmp_ln40_1_reg_798 <= icmp_ln40_1_fu_589_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                icmp_ln40_reg_794 <= icmp_ln40_fu_574_p2;
                tmp_7_reg_784 <= input_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_ln42_reg_841 <= icmp_ln42_fu_704_p2;
                    zext_ln42_reg_836(1 downto 0) <= zext_ln42_fu_686_p1(1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                input_size_read_reg_747 <= input_size_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    zext_ln42_1_reg_802(6 downto 0) <= zext_ln42_1_fu_605_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln42_1_reg_802(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    zext_ln42_reg_836(63 downto 2) <= "00000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, input_stream_empty_n, code_stream_full_n, input_size_empty_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln35_fu_569_p2, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln40_1_reg_798, icmp_ln42_reg_841, ap_CS_fsm_state7, icmp_ln42_1_fu_723_p2, ap_predicate_op102_write_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((input_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((input_stream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or (icmp_ln40_1_fu_589_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif ((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or ((icmp_ln40_1_reg_798 = ap_const_lv1_0) or ((icmp_ln42_1_fu_723_p2 = ap_const_lv1_1) and (icmp_ln42_reg_841 = ap_const_lv1_1)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln40_fu_728_p2 <= std_logic_vector(unsigned(found_reg_453) + unsigned(ap_const_lv31_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, input_size_empty_n)
    begin
                ap_block_state1 <= ((input_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, icmp_ln35_fu_569_p2)
    begin
                ap_block_state4 <= (((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(code_stream_full_n, ap_predicate_op102_write_state5)
    begin
                ap_block_state5 <= ((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_p_1_phi_fu_444_p4 <= p_1_reg_435;

    ap_phi_mux_p_3_phi_fu_468_p4_assign_proc : process(icmp_ln40_reg_794, icmp_ln40_1_reg_798, icmp_ln42_reg_841, ap_CS_fsm_state7, icmp_ln42_1_fu_723_p2, found_reg_453, p_3_reg_465)
    begin
        if (((icmp_ln40_reg_794 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln42_1_fu_723_p2 = ap_const_lv1_1) and (icmp_ln42_reg_841 = ap_const_lv1_1) and (icmp_ln40_1_reg_798 = ap_const_lv1_1))) then 
            ap_phi_mux_p_3_phi_fu_468_p4 <= found_reg_453;
        else 
            ap_phi_mux_p_3_phi_fu_468_p4 <= p_3_reg_465;
        end if; 
    end process;


    ap_predicate_op102_write_state5_assign_proc : process(icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794)
    begin
                ap_predicate_op102_write_state5 <= ((icmp_ln40_reg_794 = ap_const_lv1_0) or (icmp_ln40_1_fu_589_p2 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;

    code_stream_blk_n_assign_proc : process(code_stream_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or (icmp_ln40_1_fu_589_p2 = ap_const_lv1_0))) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            code_stream_blk_n <= code_stream_full_n;
        else 
            code_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    code_stream_din_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2, ap_CS_fsm_state5, ap_phi_mux_p_1_phi_fu_444_p4, p_1_reg_435, ap_predicate_op102_write_state5)
    begin
        if ((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_predicate_op102_write_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            code_stream_din <= p_1_reg_435;
        elsif ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            code_stream_din <= ap_phi_mux_p_1_phi_fu_444_p4;
        else 
            code_stream_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    code_stream_write_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2, ap_CS_fsm_state5, ap_predicate_op102_write_state5)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_predicate_op102_write_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            code_stream_write <= ap_const_logic_1;
        else 
            code_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    empty_60_fu_503_p1 <= i_reg_412(8 - 1 downto 0);
    grp_fu_481_p2 <= std_logic_vector(unsigned(out_index_fu_142) + unsigned(ap_const_lv32_1));
    i_2_fu_497_p2 <= std_logic_vector(unsigned(i_reg_412) + unsigned(ap_const_lv9_4));
    i_4_fu_734_p2 <= std_logic_vector(unsigned(i_3_reg_423) + unsigned(ap_const_lv31_1));
    icmp_ln35_fu_569_p2 <= "1" when (signed(zext_ln35_fu_565_p1) < signed(input_size_read_reg_747)) else "0";
    icmp_ln40_1_fu_589_p2 <= "1" when (signed(zext_ln40_fu_585_p1) < signed(table_size_fu_138)) else "0";
    icmp_ln40_fu_574_p2 <= "1" when (signed(table_size_fu_138) > signed(ap_const_lv32_100)) else "0";
    icmp_ln42_1_fu_723_p2 <= "1" when (tmp_1_fu_710_p6 = tmp_7_reg_784) else "0";
    icmp_ln42_fu_704_p2 <= "1" when (tmp_fu_690_p6 = p_1_reg_435) else "0";
    icmp_ln54_fu_631_p2 <= "1" when (signed(tmp_5_fu_621_p4) < signed(ap_const_lv23_1)) else "0";

    input_size_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_blk_n <= input_size_empty_n;
        else 
            input_size_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_size_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_empty_n)
    begin
        if ((not(((input_size_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_read <= ap_const_logic_1;
        else 
            input_size_read <= ap_const_logic_0;
        end if; 
    end process;


    input_stream_blk_n_assign_proc : process(input_stream_empty_n, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            input_stream_blk_n <= input_stream_empty_n;
        else 
            input_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_stream_read_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if (((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((input_stream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            input_stream_read <= ap_const_logic_1;
        else 
            input_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    local_output_code_address0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, zext_ln65_fu_580_p1, zext_ln52_fu_616_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            local_output_code_address0 <= zext_ln52_fu_616_p1(8 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_code_address0 <= zext_ln65_fu_580_p1(8 - 1 downto 0);
        else 
            local_output_code_address0 <= "XXXXXXXX";
        end if; 
    end process;


    local_output_code_ce0_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2, ap_CS_fsm_state5, ap_predicate_op102_write_state5)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            local_output_code_ce0 <= ap_const_logic_1;
        else 
            local_output_code_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_output_code_d0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_phi_mux_p_1_phi_fu_444_p4, p_1_reg_435)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            local_output_code_d0 <= p_1_reg_435;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_output_code_d0 <= ap_phi_mux_p_1_phi_fu_444_p4;
        else 
            local_output_code_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    local_output_code_we0_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_predicate_op102_write_state5)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and ((icmp_ln40_reg_794 = ap_const_lv1_0) or (icmp_ln40_1_fu_589_p2 = ap_const_lv1_0))) or (not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            local_output_code_we0 <= ap_const_logic_1;
        else 
            local_output_code_we0 <= ap_const_logic_0;
        end if; 
    end process;


    local_output_size_out1_blk_n_assign_proc : process(local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if (((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            local_output_size_out1_blk_n <= local_output_size_out1_full_n;
        else 
            local_output_size_out1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    local_output_size_out1_din <= grp_fu_481_p2;

    local_output_size_out1_write_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            local_output_size_out1_write <= ap_const_logic_1;
        else 
            local_output_size_out1_write <= ap_const_logic_0;
        end if; 
    end process;


    local_output_size_out_blk_n_assign_proc : process(local_output_size_out_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if (((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            local_output_size_out_blk_n <= local_output_size_out_full_n;
        else 
            local_output_size_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    local_output_size_out_din <= grp_fu_481_p2;

    local_output_size_out_write_assign_proc : process(input_stream_empty_n, code_stream_full_n, local_output_size_out_full_n, local_output_size_out1_full_n, ap_CS_fsm_state4, icmp_ln35_fu_569_p2)
    begin
        if ((not((((icmp_ln35_fu_569_p2 = ap_const_lv1_1) and (input_stream_empty_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out1_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (local_output_size_out_full_n = ap_const_logic_0)) or ((icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (code_stream_full_n = ap_const_logic_0)))) and (icmp_ln35_fu_569_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            local_output_size_out_write <= ap_const_logic_1;
        else 
            local_output_size_out_write <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln1_fu_595_p4 <= found_reg_453(8 downto 2);
    lshr_ln2_fu_641_p4 <= table_size_fu_138(8 downto 2);
    lshr_ln_fu_508_p4 <= i_reg_412(7 downto 2);
    or_ln29_1_fu_537_p2 <= (empty_60_fu_503_p1 or ap_const_lv8_2);
    or_ln29_2_fu_544_p2 <= (empty_60_fu_503_p1 or ap_const_lv8_3);
    or_ln29_fu_530_p2 <= (empty_60_fu_503_p1 or ap_const_lv8_1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    sext_ln32_fu_551_p0 <= input_stream_dout;
        sext_ln32_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln32_fu_551_p0),32));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    table_character_0_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, zext_ln42_1_reg_802, ap_CS_fsm_state6, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            table_character_0_address0 <= zext_ln42_1_reg_802(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_0_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_0_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_character_0_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_character_0_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_predicate_op102_write_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_character_0_ce0 <= ap_const_logic_1;
        else 
            table_character_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_0_d0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, tmp_7_reg_784, empty_60_fu_503_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_0_d0 <= tmp_7_reg_784;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_0_d0 <= empty_60_fu_503_p1;
        else 
            table_character_0_d0 <= "XXXXXXXX";
        end if; 
    end process;


    table_character_0_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_character_0_we0 <= ap_const_logic_1;
        else 
            table_character_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_1_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, zext_ln42_1_reg_802, ap_CS_fsm_state6, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            table_character_1_address0 <= zext_ln42_1_reg_802(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_1_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_1_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_character_1_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_character_1_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_predicate_op102_write_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_character_1_ce0 <= ap_const_logic_1;
        else 
            table_character_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_1_d0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, tmp_7_reg_784, or_ln29_fu_530_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_1_d0 <= tmp_7_reg_784;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_1_d0 <= or_ln29_fu_530_p2;
        else 
            table_character_1_d0 <= "XXXXXXXX";
        end if; 
    end process;


    table_character_1_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_character_1_we0 <= ap_const_logic_1;
        else 
            table_character_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_2_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, zext_ln42_1_reg_802, ap_CS_fsm_state6, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            table_character_2_address0 <= zext_ln42_1_reg_802(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_2_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_2_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_character_2_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_character_2_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_predicate_op102_write_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_character_2_ce0 <= ap_const_logic_1;
        else 
            table_character_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_2_d0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, tmp_7_reg_784, or_ln29_1_fu_537_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_2_d0 <= tmp_7_reg_784;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_2_d0 <= or_ln29_1_fu_537_p2;
        else 
            table_character_2_d0 <= "XXXXXXXX";
        end if; 
    end process;


    table_character_2_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_character_2_we0 <= ap_const_logic_1;
        else 
            table_character_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_3_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, zext_ln42_1_reg_802, ap_CS_fsm_state6, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            table_character_3_address0 <= zext_ln42_1_reg_802(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_3_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_3_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_character_3_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_character_3_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_predicate_op102_write_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_character_3_ce0 <= ap_const_logic_1;
        else 
            table_character_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_character_3_d0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state2, tmp_7_reg_784, or_ln29_2_fu_544_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            table_character_3_d0 <= tmp_7_reg_784;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_character_3_d0 <= or_ln29_2_fu_544_p2;
        else 
            table_character_3_d0 <= "XXXXXXXX";
        end if; 
    end process;


    table_character_3_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_character_3_we0 <= ap_const_logic_1;
        else 
            table_character_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_0_address0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, zext_ln42_1_fu_605_p1, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_0_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif (((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            table_prefix_code_0_address0 <= zext_ln42_1_fu_605_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_0_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_prefix_code_0_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_prefix_code_0_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_prefix_code_0_ce0 <= ap_const_logic_1;
        else 
            table_prefix_code_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_0_d0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, p_1_reg_435, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_0_d0 <= p_1_reg_435;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_0_d0 <= ap_const_lv32_FFFFFFFF;
        else 
            table_prefix_code_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    table_prefix_code_0_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_0) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_prefix_code_0_we0 <= ap_const_logic_1;
        else 
            table_prefix_code_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_1_address0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, zext_ln42_1_fu_605_p1, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_1_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif (((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            table_prefix_code_1_address0 <= zext_ln42_1_fu_605_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_1_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_prefix_code_1_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_prefix_code_1_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_prefix_code_1_ce0 <= ap_const_logic_1;
        else 
            table_prefix_code_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_1_d0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, p_1_reg_435, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_1_d0 <= p_1_reg_435;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_1_d0 <= ap_const_lv32_FFFFFFFF;
        else 
            table_prefix_code_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    table_prefix_code_1_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_1) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_prefix_code_1_we0 <= ap_const_logic_1;
        else 
            table_prefix_code_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_2_address0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, zext_ln42_1_fu_605_p1, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_2_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif (((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            table_prefix_code_2_address0 <= zext_ln42_1_fu_605_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_2_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_prefix_code_2_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_prefix_code_2_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_prefix_code_2_ce0 <= ap_const_logic_1;
        else 
            table_prefix_code_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_2_d0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, p_1_reg_435, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_2_d0 <= p_1_reg_435;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_2_d0 <= ap_const_lv32_FFFFFFFF;
        else 
            table_prefix_code_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    table_prefix_code_2_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_2) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_prefix_code_2_we0 <= ap_const_logic_1;
        else 
            table_prefix_code_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_3_address0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, zext_ln42_1_fu_605_p1, zext_ln28_fu_518_p1, zext_ln55_fu_651_p1, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_3_address0 <= zext_ln55_fu_651_p1(7 - 1 downto 0);
        elsif (((icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            table_prefix_code_3_address0 <= zext_ln42_1_fu_605_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_3_address0 <= zext_ln28_fu_518_p1(7 - 1 downto 0);
        else 
            table_prefix_code_3_address0 <= "XXXXXXX";
        end if; 
    end process;


    table_prefix_code_3_ce0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or (not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (icmp_ln40_reg_794 = ap_const_lv1_1) and (icmp_ln40_1_fu_589_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
            table_prefix_code_3_ce0 <= ap_const_logic_1;
        else 
            table_prefix_code_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_prefix_code_3_d0_assign_proc : process(ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, p_1_reg_435, icmp_ln54_fu_631_p2, trunc_ln55_fu_637_p1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1))))) then 
            table_prefix_code_3_d0 <= p_1_reg_435;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_prefix_code_3_d0 <= ap_const_lv32_FFFFFFFF;
        else 
            table_prefix_code_3_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    table_prefix_code_3_we0_assign_proc : process(code_stream_full_n, ap_CS_fsm_state5, icmp_ln40_1_fu_589_p2, icmp_ln40_reg_794, ap_CS_fsm_state2, tmp_2_fu_489_p3, icmp_ln54_fu_631_p2, ap_predicate_op102_write_state5, trunc_ln55_fu_637_p1)
    begin
        if (((not(((code_stream_full_n = ap_const_logic_0) and (ap_predicate_op102_write_state5 = ap_const_boolean_1))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (((icmp_ln40_reg_794 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)) or ((icmp_ln40_1_fu_589_p2 = ap_const_lv1_0) and (trunc_ln55_fu_637_p1 = ap_const_lv2_3) and (icmp_ln54_fu_631_p2 = ap_const_lv1_1)))) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_2_fu_489_p3 = ap_const_lv1_0)))) then 
            table_prefix_code_3_we0 <= ap_const_logic_1;
        else 
            table_prefix_code_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    table_size_1_fu_666_p2 <= std_logic_vector(unsigned(table_size_fu_138) + unsigned(ap_const_lv32_1));
    tmp_2_fu_489_p3 <= i_reg_412(8 downto 8);
    tmp_5_fu_621_p4 <= table_size_fu_138(31 downto 9);
    tmp_fu_690_p5 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln42_fu_682_p1),64));
    trunc_ln42_fu_682_p1 <= found_reg_453(2 - 1 downto 0);
    trunc_ln55_fu_637_p1 <= table_size_fu_138(2 - 1 downto 0);
    zext_ln28_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_508_p4),64));
    zext_ln32_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_784),31));
    zext_ln35_1_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_p_3_phi_fu_468_p4),32));
    zext_ln35_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_423),32));
    zext_ln40_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(found_reg_453),32));
    zext_ln42_1_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_595_p4),64));
    zext_ln42_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln42_fu_682_p1),64));
    zext_ln52_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_index_fu_142),64));
    zext_ln55_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_641_p4),64));
    zext_ln65_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_index_fu_142),64));
end behav;
